export const environment = {
    production: true,

    rootUrl: "http://localhost:8080/api/auth", //  url in use
    baseUrl: "http://localhost:8080/api/test",
    gateUrl: "http://localhost:8080/api",
    lineUrl: "http://localhost:8080/api/admin",
    ptoUrl: "http://localhost:8080/api/auth",
    ptoListUrl: "http://localhost:8080/vendor",
    ptoIdUrl: "http://localhost:8080/vendor",
    userlist: "http://localhost:8080/api/activeuser",
    configUrl: "http://localhost:8080/api",
    complainListUrl: "http://localhost:8080/api/auth",
    mailUrl: "http://localhost:8080/sendMail",
    alarmUrl: "http://localhost:8080/api/alarm",
    dbUrl: "http://localhost:8080/api",
    eventUrl: "http://localhost:8080/api",
    ntpUrl: "http://localhost:8080/api",
    transactionUrl: "http://localhost:8080/api",
    generalmsgUrl: "http://localhost:8080/api",
    maintenanceStaffListUrl: "http://localhost:8080/api",
    productType: "http://localhost:8080/api/product",
    productUrl: "http://localhost:8080/api/afc", //  url in use
    equipmentUrl: "http://localhost:8080/api/equipment",
    productById: "http://localhost:8080/api/singleinventory",
    equipmentByUrl: "http://localhost:8080/api/singleequipment",
    directionUrl: "http://localhost:8080/api/gatedirection",
    stationGateDir: "http://localhost:8080/api/direction",
    terminalUrl: "http://localhost:8080/api/terminal",
    shiftsUrl: "http://localhost:8080/api/usershift",
    createUserUrl: "http://localhost:8080/api/createuser/add",
    assignUserURL: "http://localhost:8080/api/usertostation",
};
